name: Sprout Local
values:
  - key: baseUrl
    value: 'http://localhost:8080'
    enabled: true
    type: default
  - key: auth0Domain
    value: 'dev-ryjmw8xnz7n315j0.us.auth0.com'
    enabled: true
    type: default
  - key: auth0ClientId
    value: 'TqzOSbedDJ3OuE2J2y20OcltzUwey7to'
    enabled: true
    type: default
  - key: auth0Audience
    value: 'https://api.sprout.app'
    enabled: true
    type: default
