run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/movsesmeliksetyan/sprout-api
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
