// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listCategories = `-- name: ListCategories :many
SELECT id, user_id, name, icon, shade, sort_order, monthly_budget_minor, category_type, archived_at, created_at, updated_at FROM categories
WHERE user_id = $1 AND ($2::boolean OR archived_at IS NULL)
ORDER BY (archived_at IS NOT NULL), sort_order, id
`

type ListCategoriesParams struct {
	UserID          uuid.UUID
	IncludeArchived bool
}

// Active categories in display order, then the archived ones when asked for.
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.UserID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Shade,
			&i.SortOrder,
			&i.MonthlyBudgetMinor,
			&i.CategoryType,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryTypes = `-- name: ListCategoryTypes :many
SELECT key, name FROM category_types ORDER BY key
`

func (q *Queries) ListCategoryTypes(ctx context.Context) ([]CategoryType, error) {
	rows, err := q.db.Query(ctx, listCategoryTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryType
	for rows.Next() {
		var i CategoryType
		if err := rows.Scan(&i.Key, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedCategory = `-- name: SeedCategory :exec
INSERT INTO categories (id, user_id, name, icon, shade, sort_order, category_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, lower(name)) WHERE archived_at IS NULL DO NOTHING
`

type SeedCategoryParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Icon         string
	Shade        int16
	SortOrder    int32
	CategoryType *string
}

// Does nothing when the user already has an active category of this name.
func (q *Queries) SeedCategory(ctx context.Context, arg SeedCategoryParams) error {
	_, err := q.db.Exec(ctx, seedCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Shade,
		arg.SortOrder,
		arg.CategoryType,
	)
	return err
}
