// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCopyTransactions implements pgx.CopyFromSource.
type iteratorForCopyTransactions struct {
	rows                 []CopyTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].Kind,
		r.rows[0].AmountMinor,
		r.rows[0].CategoryID,
		r.rows[0].Merchant,
		r.rows[0].MerchantKey,
		r.rows[0].Note,
		r.rows[0].OccurredAt,
		r.rows[0].LocalDate,
		r.rows[0].Source,
		r.rows[0].DedupHash,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForCopyTransactions) Err() error {
	return nil
}

// Bulk-loads transactions with a chosen created_at; only the seed command
// writes the ledger this way.
func (q *Queries) CopyTransactions(ctx context.Context, arg []CopyTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transactions"}, []string{"id", "user_id", "kind", "amount_minor", "category_id", "merchant", "merchant_key", "note", "occurred_at", "local_date", "source", "dedup_hash", "created_at"}, &iteratorForCopyTransactions{rows: arg})
}
