// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveGoals = `-- name: CountActiveGoals :one
SELECT count(*) FROM goals WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveGoals(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveGoals, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGoals = `-- name: CountGoals :one
SELECT count(*) FROM goals WHERE user_id = $1 AND status <> 'archived'
`

// How many goals the user's list shows: the active and the completed ones.
func (q *Queries) CountGoals(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGoals, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContribution = `-- name: CreateContribution :one
INSERT INTO goal_contributions (id, user_id, goal_id, kind, amount_minor, occurred_at, local_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, goal_id, kind, amount_minor, occurred_at, local_date, created_at
`

type CreateContributionParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	GoalID      uuid.UUID
	Kind        string
	AmountMinor int64
	OccurredAt  time.Time
	LocalDate   time.Time
}

func (q *Queries) CreateContribution(ctx context.Context, arg CreateContributionParams) (GoalContribution, error) {
	row := q.db.QueryRow(ctx, createContribution,
		arg.ID,
		arg.UserID,
		arg.GoalID,
		arg.Kind,
		arg.AmountMinor,
		arg.OccurredAt,
		arg.LocalDate,
	)
	var i GoalContribution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.Kind,
		&i.AmountMinor,
		&i.OccurredAt,
		&i.LocalDate,
		&i.CreatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (id, user_id, title, emoji, image_key, target_minor, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, emoji, image_key, target_minor, status, sort_order, completed_at, created_at, updated_at
`

type CreateGoalParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	Emoji       *string
	ImageKey    *string
	TargetMinor int64
	SortOrder   int32
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Emoji,
		arg.ImageKey,
		arg.TargetMinor,
		arg.SortOrder,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Emoji,
		&i.ImageKey,
		&i.TargetMinor,
		&i.Status,
		&i.SortOrder,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :execrows
DELETE FROM goals WHERE id = $1 AND user_id = $2
`

type DeleteGoalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGoal = `-- name: GetGoal :one
SELECT g.id, g.user_id, g.title, g.emoji, g.image_key, g.target_minor, g.status, g.sort_order, g.completed_at, g.created_at, g.updated_at,
       COALESCE((SELECT sum(CASE c.kind WHEN 'topup' THEN c.amount_minor ELSE -c.amount_minor END)
                 FROM goal_contributions c
                 WHERE c.goal_id = g.id), 0)::bigint AS saved_minor
FROM goals g
WHERE g.id = $1 AND g.user_id = $2
`

type GetGoalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetGoalRow struct {
	Goal       Goal
	SavedMinor int64
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (GetGoalRow, error) {
	row := q.db.QueryRow(ctx, getGoal, arg.ID, arg.UserID)
	var i GetGoalRow
	err := row.Scan(
		&i.Goal.ID,
		&i.Goal.UserID,
		&i.Goal.Title,
		&i.Goal.Emoji,
		&i.Goal.ImageKey,
		&i.Goal.TargetMinor,
		&i.Goal.Status,
		&i.Goal.SortOrder,
		&i.Goal.CompletedAt,
		&i.Goal.CreatedAt,
		&i.Goal.UpdatedAt,
		&i.SavedMinor,
	)
	return i, err
}

const listGoals = `-- name: ListGoals :many
SELECT g.id, g.user_id, g.title, g.emoji, g.image_key, g.target_minor, g.status, g.sort_order, g.completed_at, g.created_at, g.updated_at,
       COALESCE((SELECT sum(CASE c.kind WHEN 'topup' THEN c.amount_minor ELSE -c.amount_minor END)
                 FROM goal_contributions c
                 WHERE c.goal_id = g.id), 0)::bigint AS saved_minor
FROM goals g
WHERE g.user_id = $1 AND g.status <> 'archived'
ORDER BY g.sort_order, g.id
`

type ListGoalsRow struct {
	Goal       Goal
	SavedMinor int64
}

// The user's active and completed goals in display order, each with what is
// saved in it: top-ups minus withdrawals.
func (q *Queries) ListGoals(ctx context.Context, userID uuid.UUID) ([]ListGoalsRow, error) {
	rows, err := q.db.Query(ctx, listGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalsRow
	for rows.Next() {
		var i ListGoalsRow
		if err := rows.Scan(
			&i.Goal.ID,
			&i.Goal.UserID,
			&i.Goal.Title,
			&i.Goal.Emoji,
			&i.Goal.ImageKey,
			&i.Goal.TargetMinor,
			&i.Goal.Status,
			&i.Goal.SortOrder,
			&i.Goal.CompletedAt,
			&i.Goal.CreatedAt,
			&i.Goal.UpdatedAt,
			&i.SavedMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentContributions = `-- name: ListRecentContributions :many
SELECT id, user_id, goal_id, kind, amount_minor, occurred_at, local_date, created_at FROM goal_contributions
WHERE goal_id = $1 AND user_id = $2
ORDER BY occurred_at DESC, id DESC
LIMIT $3
`

type ListRecentContributionsParams struct {
	GoalID   uuid.UUID
	UserID   uuid.UUID
	RowLimit int32
}

// The newest contributions of one of the user's goals.
func (q *Queries) ListRecentContributions(ctx context.Context, arg ListRecentContributionsParams) ([]GoalContribution, error) {
	rows, err := q.db.Query(ctx, listRecentContributions, arg.GoalID, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalContribution
	for rows.Next() {
		var i GoalContribution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.Kind,
			&i.AmountMinor,
			&i.OccurredAt,
			&i.LocalDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextGoalSortOrder = `-- name: NextGoalSortOrder :one
SELECT (COALESCE(max(sort_order), -1) + 1)::integer FROM goals WHERE user_id = $1
`

// The position after the user's last goal.
func (q *Queries) NextGoalSortOrder(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextGoalSortOrder, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET title        = $3,
    emoji        = $4,
    image_key    = $5,
    target_minor = $6,
    status       = $7,
    sort_order   = $8,
    completed_at = $9
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, emoji, image_key, target_minor, status, sort_order, completed_at, created_at, updated_at
`

type UpdateGoalParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	Emoji       *string
	ImageKey    *string
	TargetMinor int64
	Status      string
	SortOrder   int32
	CompletedAt *time.Time
}

// Writes the goal as given: the caller reads it, changes what it must and
// sends every column back.
func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Emoji,
		arg.ImageKey,
		arg.TargetMinor,
		arg.Status,
		arg.SortOrder,
		arg.CompletedAt,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Emoji,
		&i.ImageKey,
		&i.TargetMinor,
		&i.Status,
		&i.SortOrder,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
