// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: home.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const ledgerNet = `-- name: LedgerNet :one
SELECT COALESCE(sum(CASE kind WHEN 'income' THEN amount_minor ELSE -amount_minor END), 0)::bigint
FROM transactions
WHERE user_id = $1
`

// Everything the user's transactions add up to: income minus expense.
func (q *Queries) LedgerNet(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, ledgerNet, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const spentBetween = `-- name: SpentBetween :one
SELECT COALESCE(sum(amount_minor), 0)::bigint
FROM transactions
WHERE user_id = $1
  AND kind = 'expense'
  AND local_date BETWEEN $2::date AND $3::date
`

type SpentBetweenParams struct {
	UserID   uuid.UUID
	FromDate time.Time
	ToDate   time.Time
}

// The user's expenses on the calendar days from_date to to_date, both
// included.
func (q *Queries) SpentBetween(ctx context.Context, arg SpentBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, spentBetween, arg.UserID, arg.FromDate, arg.ToDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const spentByCategory = `-- name: SpentByCategory :many
SELECT c.id AS category_id, sum(t.amount_minor)::bigint AS spent_minor
FROM transactions t
JOIN categories c ON c.id = t.category_id AND c.user_id = t.user_id
WHERE t.user_id = $1
  AND t.kind = 'expense'
  AND t.local_date BETWEEN $2::date AND $3::date
GROUP BY c.id, c.sort_order
ORDER BY spent_minor DESC, c.sort_order, c.id
`

type SpentByCategoryParams struct {
	UserID   uuid.UUID
	FromDate time.Time
	ToDate   time.Time
}

type SpentByCategoryRow struct {
	CategoryID uuid.UUID
	SpentMinor int64
}

// The user's expenses on the calendar days from_date to to_date per
// category, largest first; categories without any are left out. Equal
// amounts come in display order.
func (q *Queries) SpentByCategory(ctx context.Context, arg SpentByCategoryParams) ([]SpentByCategoryRow, error) {
	rows, err := q.db.Query(ctx, spentByCategory, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpentByCategoryRow
	for rows.Next() {
		var i SpentByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.SpentMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
