// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acquireIdempotencyKey = `-- name: AcquireIdempotencyKey :one
INSERT INTO idempotency_keys (user_id, key, request_hash, locked_until, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, key) DO UPDATE
SET request_hash          = EXCLUDED.request_hash,
    status                = 'processing',
    locked_until          = EXCLUDED.locked_until,
    response_status       = NULL,
    response_content_type = NULL,
    response_body         = NULL,
    expires_at            = EXCLUDED.expires_at,
    created_at            = now()
WHERE idempotency_keys.expires_at <= now()
   OR (idempotency_keys.status = 'processing' AND idempotency_keys.locked_until <= now())
RETURNING user_id, key, request_hash, status, locked_until, response_status, response_content_type, response_body, expires_at, created_at
`

type AcquireIdempotencyKeyParams struct {
	UserID      uuid.UUID
	Key         uuid.UUID
	RequestHash []byte
	LockedUntil time.Time
	ExpiresAt   time.Time
}

// Claims the key for a request. Returns a row only to the request that now
// owns it: the key is new, has expired, or belongs to a request that never
// finished.
func (q *Queries) AcquireIdempotencyKey(ctx context.Context, arg AcquireIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, acquireIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.RequestHash,
		arg.LockedUntil,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.RequestHash,
		&i.Status,
		&i.LockedUntil,
		&i.ResponseStatus,
		&i.ResponseContentType,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :execrows
UPDATE idempotency_keys
SET status = 'completed', response_status = $4, response_content_type = $5, response_body = $6
WHERE user_id = $1 AND key = $2 AND status = 'processing' AND locked_until = $3
`

type CompleteIdempotencyKeyParams struct {
	UserID              uuid.UUID
	Key                 uuid.UUID
	LockedUntil         time.Time
	ResponseStatus      *int32
	ResponseContentType *string
	ResponseBody        []byte
}

// Stores the response to replay. locked_until tells the owner apart from a
// request that took the key over.
func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.LockedUntil,
		arg.ResponseStatus,
		arg.ResponseContentType,
		arg.ResponseBody,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_id, key, request_hash, status, locked_until, response_status, response_content_type, response_body, expires_at, created_at FROM idempotency_keys WHERE user_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserID uuid.UUID
	Key    uuid.UUID
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.RequestHash,
		&i.Status,
		&i.LockedUntil,
		&i.ResponseStatus,
		&i.ResponseContentType,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :execrows
DELETE FROM idempotency_keys
WHERE user_id = $1 AND key = $2 AND status = 'processing' AND locked_until = $3
`

type ReleaseIdempotencyKeyParams struct {
	UserID      uuid.UUID
	Key         uuid.UUID
	LockedUntil time.Time
}

// Gives the key up so that a retry runs again.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.UserID, arg.Key, arg.LockedUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
