// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Name               string
	Icon               string
	Shade              int16
	SortOrder          int32
	MonthlyBudgetMinor int64
	CategoryType       *string
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type CategoryType struct {
	Key  string
	Name string
}

type IdempotencyKey struct {
	UserID              uuid.UUID
	Key                 uuid.UUID
	RequestHash         []byte
	Status              string
	LockedUntil         time.Time
	ResponseStatus      *int32
	ResponseContentType *string
	ResponseBody        []byte
	ExpiresAt           time.Time
	CreatedAt           time.Time
}

type Upload struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Purpose     string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Filename    *string
	Status      string
	ExpiresAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID                   uuid.UUID
	Auth0Sub             string
	Email                string
	Name                 string
	AvatarKey            *string
	Currency             string
	Timezone             string
	StartingBalanceMinor int64
	OnboardingCompleted  bool
	NotificationsEnabled bool
	BudgetAlerts         bool
	WeeklyRecap          bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
