// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Claims the key for a request. Returns a row only to the request that now
	// owns it: the key is new, has expired, or belongs to a request that never
	// finished.
	AcquireIdempotencyKey(ctx context.Context, arg AcquireIdempotencyKeyParams) (IdempotencyKey, error)
	// How many calendar days in a row, ending today or yesterday, the user
	// created at least one transaction on. Days are read in the given timezone.
	// Each run of consecutive days is an island: within one, the day minus its
	// rank is the same date.
	ActivityStreak(ctx context.Context, arg ActivityStreakParams) (int64, error)
	CategoryHasTransactions(ctx context.Context, arg CategoryHasTransactionsParams) (bool, error)
	// Whether another active category of the user has this name, in any case.
	CategoryNameTaken(ctx context.Context, arg CategoryNameTakenParams) (bool, error)
	// Stores the response to replay. locked_until tells the owner apart from a
	// request that took the key over.
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (int64, error)
	// Returns no row unless the upload is the user's and still pending.
	ConsumeUpload(ctx context.Context, arg ConsumeUploadParams) (Upload, error)
	CountActiveCategories(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	// Returns no row when a user with this auth0_sub already exists.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	// Locks the row until the database transaction ends.
	GetTransactionForUpdate(ctx context.Context, arg GetTransactionForUpdateParams) (Transaction, error)
	GetUpload(ctx context.Context, arg GetUploadParams) (Upload, error)
	GetUserByAuth0Sub(ctx context.Context, auth0Sub string) (User, error)
	// Locks the row until the transaction ends.
	GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	// Everything the user's transactions add up to: income minus expense.
	LedgerNet(ctx context.Context, userID uuid.UUID) (int64, error)
	// Active categories in display order, then the archived ones when asked for.
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListCategoryTypes(ctx context.Context) ([]CategoryType, error)
	// The whole-day totals of the given days under the same filters as
	// ListTransactions: income minus expense, and how many transactions.
	ListDayTotals(ctx context.Context, arg ListDayTotalsParams) ([]ListDayTotalsRow, error)
	// A page of the user's transactions, newest first. A null filter is not
	// applied. The cursor is the last row of the previous page.
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	// The position after the user's last active category.
	NextCategorySortOrder(ctx context.Context, userID uuid.UUID) (int32, error)
	Ping(ctx context.Context) (int32, error)
	// Gives the key up so that a retry runs again.
	ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) (int64, error)
	// Puts the user's categories in the order of ids.
	ReorderCategories(ctx context.Context, arg ReorderCategoriesParams) error
	// Does nothing when the user already has an active category of this name.
	SeedCategory(ctx context.Context, arg SeedCategoryParams) error
	// The user's expenses on the calendar days from_date to to_date, both
	// included.
	SpentBetween(ctx context.Context, arg SpentBetweenParams) (int64, error)
	// The user's expenses on the calendar days from_date to to_date per
	// category, largest first; categories without any are left out. Equal
	// amounts come in display order.
	SpentByCategory(ctx context.Context, arg SpentByCategoryParams) ([]SpentByCategoryRow, error)
	// A null argument leaves its column as it is. Archiving an archived category
	// keeps the time it was first archived.
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	// Sets the budget of ids[i] to amounts[i].
	UpdateCategoryBudgets(ctx context.Context, arg UpdateCategoryBudgetsParams) error
	// Writes every field a user can change; the caller sends the ones that stay
	// as they are.
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	// A null argument leaves its column as it is.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UserHasTransactions(ctx context.Context, userID uuid.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
