// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activityStreak = `-- name: ActivityStreak :one
WITH days AS (
    SELECT (t.created_at AT TIME ZONE $2::text)::date AS day
    FROM transactions t
    WHERE t.user_id = $3
    UNION
    SELECT (c.created_at AT TIME ZONE $2::text)::date
    FROM goal_contributions c
    WHERE c.user_id = $3
),
islands AS (
    SELECT day, day - (row_number() OVER (ORDER BY day))::integer AS island
    FROM days
    WHERE day <= $1::date
)
SELECT count(*)
FROM islands
WHERE island = (
    SELECT island FROM islands
    WHERE day >= $1::date - 1
    ORDER BY day DESC
    LIMIT 1
)
`

type ActivityStreakParams struct {
	Today    time.Time
	Timezone string
	UserID   uuid.UUID
}

// How many calendar days in a row, ending today or yesterday, the user
// created at least one transaction or goal contribution on. Days are read in
// the given timezone.
// Each run of consecutive days is an island: within one, the day minus its
// rank is the same date.
func (q *Queries) ActivityStreak(ctx context.Context, arg ActivityStreakParams) (int64, error) {
	row := q.db.QueryRow(ctx, activityStreak, arg.Today, arg.Timezone, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
