// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summary.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const categorySpending = `-- name: CategorySpending :many
SELECT c.id AS category_id,
       c.monthly_budget_minor,
       COALESCE(sum(t.amount_minor) FILTER (WHERE t.local_date >= $1::date), 0)::bigint AS spent_minor,
       (count(t.id) FILTER (WHERE t.local_date >= $1::date))::integer AS txn_count,
       COALESCE(sum(t.amount_minor) FILTER (WHERE t.local_date < $1::date), 0)::bigint AS previous_spent_minor
FROM categories c
LEFT JOIN transactions t ON t.category_id = c.id
    AND t.user_id = c.user_id
    AND t.kind = 'expense'
    AND t.local_date BETWEEN $2::date AND $3::date
WHERE c.user_id = $4
GROUP BY c.id
HAVING c.archived_at IS NULL
    OR count(t.id) FILTER (WHERE t.local_date >= $1::date) > 0
ORDER BY spent_minor DESC, c.sort_order, c.id
`

type CategorySpendingParams struct {
	FromDate         time.Time
	PreviousFromDate time.Time
	ToDate           time.Time
	UserID           uuid.UUID
}

type CategorySpendingRow struct {
	CategoryID         uuid.UUID
	MonthlyBudgetMinor int64
	SpentMinor         int64
	TxnCount           int32
	PreviousSpentMinor int64
}

// Every active category of the user with its expenses on the calendar days
// from_date to to_date, and on the days from previous_from_date up to
// from_date, the period before. An archived category is included only when
// it has expenses in the period. Largest first; equal amounts come in
// display order.
func (q *Queries) CategorySpending(ctx context.Context, arg CategorySpendingParams) ([]CategorySpendingRow, error) {
	rows, err := q.db.Query(ctx, categorySpending,
		arg.FromDate,
		arg.PreviousFromDate,
		arg.ToDate,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategorySpendingRow
	for rows.Next() {
		var i CategorySpendingRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.MonthlyBudgetMinor,
			&i.SpentMinor,
			&i.TxnCount,
			&i.PreviousSpentMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categorySpentByDay = `-- name: CategorySpentByDay :many
SELECT local_date,
       sum(amount_minor)::bigint AS spent_minor,
       count(*)::integer AS txn_count
FROM transactions
WHERE user_id = $1
  AND category_id = $2::uuid
  AND kind = 'expense'
  AND local_date BETWEEN $3::date AND $4::date
GROUP BY local_date
ORDER BY local_date
`

type CategorySpentByDayParams struct {
	UserID     uuid.UUID
	CategoryID uuid.UUID
	FromDate   time.Time
	ToDate     time.Time
}

type CategorySpentByDayRow struct {
	LocalDate  time.Time
	SpentMinor int64
	TxnCount   int32
}

// The user's expenses in one category on the calendar days from_date to
// to_date, both included, day by day; days without any are left out.
func (q *Queries) CategorySpentByDay(ctx context.Context, arg CategorySpentByDayParams) ([]CategorySpentByDayRow, error) {
	rows, err := q.db.Query(ctx, categorySpentByDay,
		arg.UserID,
		arg.CategoryID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategorySpentByDayRow
	for rows.Next() {
		var i CategorySpentByDayRow
		if err := rows.Scan(&i.LocalDate, &i.SpentMinor, &i.TxnCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
