// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions_list.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listDayTotals = `-- name: ListDayTotals :many
SELECT local_date,
       sum(CASE kind WHEN 'income' THEN amount_minor ELSE -amount_minor END)::bigint AS net_minor,
       count(*) AS count
FROM transactions
WHERE user_id = $1
  AND local_date = ANY ($2::date[])
  AND ($3::date IS NULL OR local_date >= $3::date)
  AND ($4::date IS NULL OR local_date <= $4::date)
  AND ($5::uuid IS NULL OR category_id = $5::uuid)
  AND ($6::text IS NULL OR kind = $6::text)
  AND ($7::text IS NULL OR merchant ILIKE $7::text OR note ILIKE $7::text)
GROUP BY local_date
ORDER BY local_date DESC
`

type ListDayTotalsParams struct {
	UserID     uuid.UUID
	Dates      []time.Time
	FromDate   *time.Time
	ToDate     *time.Time
	CategoryID *uuid.UUID
	Kind       *string
	Pattern    *string
}

type ListDayTotalsRow struct {
	LocalDate time.Time
	NetMinor  int64
	Count     int64
}

// The whole-day totals of the given days under the same filters as
// ListTransactions: income minus expense, and how many transactions.
func (q *Queries) ListDayTotals(ctx context.Context, arg ListDayTotalsParams) ([]ListDayTotalsRow, error) {
	rows, err := q.db.Query(ctx, listDayTotals,
		arg.UserID,
		arg.Dates,
		arg.FromDate,
		arg.ToDate,
		arg.CategoryID,
		arg.Kind,
		arg.Pattern,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDayTotalsRow
	for rows.Next() {
		var i ListDayTotalsRow
		if err := rows.Scan(&i.LocalDate, &i.NetMinor, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, kind, amount_minor, category_id, merchant, merchant_key, note, occurred_at, local_date, source, import_id, receipt_id, dedup_hash, created_at, updated_at FROM transactions
WHERE user_id = $1
  AND ($2::date IS NULL OR local_date >= $2::date)
  AND ($3::date IS NULL OR local_date <= $3::date)
  AND ($4::uuid IS NULL OR category_id = $4::uuid)
  AND ($5::text IS NULL OR kind = $5::text)
  AND ($6::text IS NULL OR merchant ILIKE $6::text OR note ILIKE $6::text)
  AND ($7::date IS NULL
       OR (local_date, id) < ($7::date, $8::uuid))
ORDER BY local_date DESC, id DESC
LIMIT $9
`

type ListTransactionsParams struct {
	UserID     uuid.UUID
	FromDate   *time.Time
	ToDate     *time.Time
	CategoryID *uuid.UUID
	Kind       *string
	Pattern    *string
	CursorDate *time.Time
	CursorID   *uuid.UUID
	RowLimit   int32
}

// A page of the user's transactions, newest first. A null filter is not
// applied. The cursor is the last row of the previous page.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.CategoryID,
		arg.Kind,
		arg.Pattern,
		arg.CursorDate,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.AmountMinor,
			&i.CategoryID,
			&i.Merchant,
			&i.MerchantKey,
			&i.Note,
			&i.OccurredAt,
			&i.LocalDate,
			&i.Source,
			&i.ImportID,
			&i.ReceiptID,
			&i.DedupHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
