// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const categoryHasTransactions = `-- name: CategoryHasTransactions :one
SELECT EXISTS (SELECT 1 FROM transactions WHERE user_id = $1 AND category_id = $2)
`

type CategoryHasTransactionsParams struct {
	UserID     uuid.UUID
	CategoryID *uuid.UUID
}

func (q *Queries) CategoryHasTransactions(ctx context.Context, arg CategoryHasTransactionsParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryHasTransactions, arg.UserID, arg.CategoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, user_id, kind, amount_minor, category_id, merchant, merchant_key, note,
                          occurred_at, local_date, source, import_id, receipt_id, dedup_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, kind, amount_minor, category_id, merchant, merchant_key, note, occurred_at, local_date, source, import_id, receipt_id, dedup_hash, created_at, updated_at
`

type CreateTransactionParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Kind        string
	AmountMinor int64
	CategoryID  *uuid.UUID
	Merchant    *string
	MerchantKey string
	Note        *string
	OccurredAt  time.Time
	LocalDate   time.Time
	Source      string
	ImportID    *uuid.UUID
	ReceiptID   *uuid.UUID
	DedupHash   []byte
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.AmountMinor,
		arg.CategoryID,
		arg.Merchant,
		arg.MerchantKey,
		arg.Note,
		arg.OccurredAt,
		arg.LocalDate,
		arg.Source,
		arg.ImportID,
		arg.ReceiptID,
		arg.DedupHash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.AmountMinor,
		&i.CategoryID,
		&i.Merchant,
		&i.MerchantKey,
		&i.Note,
		&i.OccurredAt,
		&i.LocalDate,
		&i.Source,
		&i.ImportID,
		&i.ReceiptID,
		&i.DedupHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, kind, amount_minor, category_id, merchant, merchant_key, note, occurred_at, local_date, source, import_id, receipt_id, dedup_hash, created_at, updated_at FROM transactions WHERE id = $1 AND user_id = $2
`

type GetTransactionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.AmountMinor,
		&i.CategoryID,
		&i.Merchant,
		&i.MerchantKey,
		&i.Note,
		&i.OccurredAt,
		&i.LocalDate,
		&i.Source,
		&i.ImportID,
		&i.ReceiptID,
		&i.DedupHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionForUpdate = `-- name: GetTransactionForUpdate :one
SELECT id, user_id, kind, amount_minor, category_id, merchant, merchant_key, note, occurred_at, local_date, source, import_id, receipt_id, dedup_hash, created_at, updated_at FROM transactions WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type GetTransactionForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Locks the row until the database transaction ends.
func (q *Queries) GetTransactionForUpdate(ctx context.Context, arg GetTransactionForUpdateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionForUpdate, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.AmountMinor,
		&i.CategoryID,
		&i.Merchant,
		&i.MerchantKey,
		&i.Note,
		&i.OccurredAt,
		&i.LocalDate,
		&i.Source,
		&i.ImportID,
		&i.ReceiptID,
		&i.DedupHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET kind         = $1,
    amount_minor = $2,
    category_id  = $3,
    merchant     = $4,
    merchant_key = $5,
    note         = $6,
    occurred_at  = $7,
    local_date   = $8,
    dedup_hash   = $9
WHERE id = $10 AND user_id = $11
RETURNING id, user_id, kind, amount_minor, category_id, merchant, merchant_key, note, occurred_at, local_date, source, import_id, receipt_id, dedup_hash, created_at, updated_at
`

type UpdateTransactionParams struct {
	Kind        string
	AmountMinor int64
	CategoryID  *uuid.UUID
	Merchant    *string
	MerchantKey string
	Note        *string
	OccurredAt  time.Time
	LocalDate   time.Time
	DedupHash   []byte
	ID          uuid.UUID
	UserID      uuid.UUID
}

// Writes every field a user can change; the caller sends the ones that stay
// as they are.
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.Kind,
		arg.AmountMinor,
		arg.CategoryID,
		arg.Merchant,
		arg.MerchantKey,
		arg.Note,
		arg.OccurredAt,
		arg.LocalDate,
		arg.DedupHash,
		arg.ID,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.AmountMinor,
		&i.CategoryID,
		&i.Merchant,
		&i.MerchantKey,
		&i.Note,
		&i.OccurredAt,
		&i.LocalDate,
		&i.Source,
		&i.ImportID,
		&i.ReceiptID,
		&i.DedupHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userHasTransactions = `-- name: UserHasTransactions :one
SELECT EXISTS (SELECT 1 FROM transactions WHERE user_id = $1)
`

func (q *Queries) UserHasTransactions(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userHasTransactions, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
