// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeUpload = `-- name: ConsumeUpload :one
UPDATE uploads
SET status = 'consumed', size_bytes = $3
WHERE id = $1 AND user_id = $2 AND status = 'pending'
RETURNING id, user_id, purpose, object_key, content_type, size_bytes, filename, status, expires_at, created_at, updated_at
`

type ConsumeUploadParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	SizeBytes int64
}

// Returns no row unless the upload is the user's and still pending.
func (q *Queries) ConsumeUpload(ctx context.Context, arg ConsumeUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, consumeUpload, arg.ID, arg.UserID, arg.SizeBytes)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Filename,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (id, user_id, purpose, object_key, content_type, size_bytes, filename, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, purpose, object_key, content_type, size_bytes, filename, status, expires_at, created_at, updated_at
`

type CreateUploadParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Purpose     string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Filename    *string
	ExpiresAt   time.Time
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Filename,
		arg.ExpiresAt,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Filename,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, user_id, purpose, object_key, content_type, size_bytes, filename, status, expires_at, created_at, updated_at FROM uploads WHERE id = $1 AND user_id = $2
`

type GetUploadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetUpload(ctx context.Context, arg GetUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, getUpload, arg.ID, arg.UserID)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Filename,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
