// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, auth0_sub, email, name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (auth0_sub) DO NOTHING
RETURNING id, auth0_sub, email, name, avatar_key, currency, timezone, starting_balance_minor, onboarding_completed, notifications_enabled, budget_alerts, weekly_recap, created_at, updated_at
`

type CreateUserParams struct {
	ID       uuid.UUID
	Auth0Sub string
	Email    string
	Name     string
}

// Returns no row when a user with this auth0_sub already exists.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Auth0Sub,
		arg.Email,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.Currency,
		&i.Timezone,
		&i.StartingBalanceMinor,
		&i.OnboardingCompleted,
		&i.NotificationsEnabled,
		&i.BudgetAlerts,
		&i.WeeklyRecap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuth0Sub = `-- name: GetUserByAuth0Sub :one
SELECT id, auth0_sub, email, name, avatar_key, currency, timezone, starting_balance_minor, onboarding_completed, notifications_enabled, budget_alerts, weekly_recap, created_at, updated_at FROM users WHERE auth0_sub = $1
`

func (q *Queries) GetUserByAuth0Sub(ctx context.Context, auth0Sub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth0Sub, auth0Sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.Currency,
		&i.Timezone,
		&i.StartingBalanceMinor,
		&i.OnboardingCompleted,
		&i.NotificationsEnabled,
		&i.BudgetAlerts,
		&i.WeeklyRecap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, auth0_sub, email, name, avatar_key, currency, timezone, starting_balance_minor, onboarding_completed, notifications_enabled, budget_alerts, weekly_recap, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

// Locks the row until the transaction ends.
func (q *Queries) GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.Currency,
		&i.Timezone,
		&i.StartingBalanceMinor,
		&i.OnboardingCompleted,
		&i.NotificationsEnabled,
		&i.BudgetAlerts,
		&i.WeeklyRecap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name                   = COALESCE($1, name),
    currency               = COALESCE($2, currency),
    timezone               = COALESCE($3, timezone),
    starting_balance_minor = COALESCE($4, starting_balance_minor),
    onboarding_completed   = COALESCE($5, onboarding_completed),
    notifications_enabled  = COALESCE($6, notifications_enabled),
    budget_alerts          = COALESCE($7, budget_alerts),
    weekly_recap           = COALESCE($8, weekly_recap),
    avatar_key             = CASE WHEN $9::boolean THEN NULL ELSE COALESCE($10, avatar_key) END
WHERE id = $11
RETURNING id, auth0_sub, email, name, avatar_key, currency, timezone, starting_balance_minor, onboarding_completed, notifications_enabled, budget_alerts, weekly_recap, created_at, updated_at
`

type UpdateUserParams struct {
	Name                 *string
	Currency             *string
	Timezone             *string
	StartingBalanceMinor *int64
	OnboardingCompleted  *bool
	NotificationsEnabled *bool
	BudgetAlerts         *bool
	WeeklyRecap          *bool
	ClearAvatar          bool
	AvatarKey            *string
	ID                   uuid.UUID
}

// A null argument leaves its column as it is.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Currency,
		arg.Timezone,
		arg.StartingBalanceMinor,
		arg.OnboardingCompleted,
		arg.NotificationsEnabled,
		arg.BudgetAlerts,
		arg.WeeklyRecap,
		arg.ClearAvatar,
		arg.AvatarKey,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.Currency,
		&i.Timezone,
		&i.StartingBalanceMinor,
		&i.OnboardingCompleted,
		&i.NotificationsEnabled,
		&i.BudgetAlerts,
		&i.WeeklyRecap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
