// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, auth0_sub, email, name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (auth0_sub) DO NOTHING
RETURNING id, auth0_sub, email, name, avatar_key, currency, timezone, starting_balance_minor, onboarding_completed, notifications_enabled, budget_alerts, weekly_recap, created_at, updated_at
`

type CreateUserParams struct {
	ID       uuid.UUID
	Auth0Sub string
	Email    string
	Name     string
}

// Returns no row when a user with this auth0_sub already exists.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Auth0Sub,
		arg.Email,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.Currency,
		&i.Timezone,
		&i.StartingBalanceMinor,
		&i.OnboardingCompleted,
		&i.NotificationsEnabled,
		&i.BudgetAlerts,
		&i.WeeklyRecap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuth0Sub = `-- name: GetUserByAuth0Sub :one
SELECT id, auth0_sub, email, name, avatar_key, currency, timezone, starting_balance_minor, onboarding_completed, notifications_enabled, budget_alerts, weekly_recap, created_at, updated_at FROM users WHERE auth0_sub = $1
`

func (q *Queries) GetUserByAuth0Sub(ctx context.Context, auth0Sub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth0Sub, auth0Sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.Currency,
		&i.Timezone,
		&i.StartingBalanceMinor,
		&i.OnboardingCompleted,
		&i.NotificationsEnabled,
		&i.BudgetAlerts,
		&i.WeeklyRecap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
